name: Mirror Branch to ISYE

on:
  push:
    branches:
      - production

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Pull CEC repo
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }}

      - name: Update CEC repository
        run: |
          cd ${{ github.event.repository.name }}
          git switch production
          git fetch --force origin
          git pull

      - name: Add the ISYE repository as a mirror
        run: |
          cd ${{ github.event.repository.name }}
          echo ISYE_MIRROR_USER
          echo $(ISYE_MIRROR_USER)
          git remote add mirror https://${ISYE_MIRROR_USER}:${{ secrets.ISYE_MIRROR_TOKEN }}@${ISYE_MIRROR_REPO}
          git fetch --force mirror

      - name: Remove the .github folder to avoid a recursive workflow
        run: |
          cd ${{ github.event.repository.name }}
          rm -rf .github

      - name: Commit the change
        run: |
          cd ${{ github.event.repository.name }}
          git config --global user.email ""
          git config --global user.name "GitHub Actions"
          git commit -a -m "[GitHub Action] Synced with CEC parent repo"

      - name: Push to the ISYE main branch
        run: |
          cd ${{ github.event.repository.name }}
          git push mirror production --force
